# Generated by Django 4.1.6 on 2023-02-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author_alter_post_publishedat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='meta_description',
        ),
    ]
