# Generated by Django 4.1.6 on 2023-02-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_meta_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-createdAt']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='publishedAt',
        ),
    ]
